version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
  build:
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: "./gradlew test"