version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0

executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2023.10.1
    environment:
      architecture: "amd64"
      platform: "linux/amd64"


workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          executor: machine_executor_amd64